-- A classroom is the tutor's room. It exists before anyone is matched into it,
-- so the student seat starts empty and is filled when a match is accepted.
alter table public.classrooms
  alter column student_id drop not null;

alter table public.classrooms
  drop constraint if exists classrooms_student_id_tutor_registry_id_key;

create unique index if not exists classrooms_student_pair_idx
  on public.classrooms (student_id, tutor_registry_id)
  where student_id is not null;

-- Three rooms per tutor; an admin raises the cap on request.
alter table public.tutors
  add column if not exists classroom_limit integer not null default 3;

create table if not exists public.classroom_slot_requests (
  id bigint generated by default as identity primary key,
  tutor_registry_id text not null references public.tutors(registry_id) on delete cascade,
  requested_by uuid references public.profiles(id) on delete set null,
  reason text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  granted integer,
  review_note text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists classroom_slot_requests_status_idx
  on public.classroom_slot_requests (status, created_at desc);

alter table public.classroom_slot_requests enable row level security;
revoke all on table public.classroom_slot_requests from public, anon, authenticated;
grant select on table public.classroom_slot_requests to authenticated;

drop policy if exists "Tutors read their slot requests" on public.classroom_slot_requests;
create policy "Tutors read their slot requests"
on public.classroom_slot_requests for select to authenticated
using (
  tutor_registry_id = (select private.current_tutor_registry_id())
  or (select private.is_admin())
);

-- A tutor decides a match request, so it needs states beyond the admin's.
alter table public.booking_requests
  drop constraint if exists booking_requests_status_check;
alter table public.booking_requests
  add constraint booking_requests_status_check
    check (status in ('new', 'contacted', 'scheduled', 'closed', 'accepted', 'declined'));

alter table public.booking_requests
  add column if not exists decided_at timestamptz,
  add column if not exists classroom_id bigint references public.classrooms(id) on delete set null;

notify pgrst, 'reload schema';
