-- Tutor cards carry a profile now, and visitors can book an intro call.

-- 1. Profile fields the tutor card renders. All optional: a tutor with none of
--    them still renders, just with fewer sections.
--
--    subject_scores: [{ "subject": "IB Economics HL", "score": "7" }]
--      replaces the single exam/score pair on the card. exam/score stay for the
--      filter rail and for records that predate this.
--    availability:   { "mon": ["18:00-21:00"], "sat": ["10:00-14:00"], ... }
--      day keys are mon..sun; each range is "HH:MM-HH:MM" in KST.
alter table public.tutors
  add column if not exists subject_scores jsonb not null default '[]'::jsonb,
  add column if not exists availability jsonb not null default '{}'::jsonb,
  add column if not exists bio text,
  add column if not exists bio_en text,
  add column if not exists video_url text,
  add column if not exists languages text,
  add column if not exists lesson_format text;

-- 2. Intro-call bookings. A visitor books without an account, so this carries
--    its own contact details rather than referencing profiles.
create table if not exists public.booking_requests (
  id bigint generated by default as identity primary key,
  tutor_registry_id text not null
    references public.tutors(registry_id) on delete cascade,
  name text not null,
  email text not null,
  phone text,
  preferred_day text,
  preferred_time text,
  note text,
  status text not null default 'new'
    check (status in ('new', 'contacted', 'scheduled', 'closed')),
  -- The admin and the tutor each clear their own flag, so one reading it does
  -- not hide it from the other.
  seen_by_admin boolean not null default false,
  seen_by_tutor boolean not null default false,
  notified_at timestamptz,
  notification_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists booking_requests_tutor_idx
  on public.booking_requests (tutor_registry_id, created_at desc);
create index if not exists booking_requests_open_idx
  on public.booking_requests (status, created_at desc);

alter table public.booking_requests enable row level security;

-- Writes arrive through the server route with the service-role key, which
-- bypasses RLS. Nothing client-side may insert or edit a booking.
revoke all on table public.booking_requests from anon, authenticated;
grant select on table public.booking_requests to authenticated;

drop policy if exists "Admins can read bookings" on public.booking_requests;
create policy "Admins can read bookings"
on public.booking_requests
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.role = 'admin'
  )
);

drop policy if exists "Tutors can read their own bookings" on public.booking_requests;
create policy "Tutors can read their own bookings"
on public.booking_requests
for select
to authenticated
using (
  tutor_registry_id = (
    select p.tutor_registry_id from public.profiles p where p.id = (select auth.uid())
  )
);
