-- Intro calls are withdrawn. A booking is now a lesson request made by a
-- signed-in student or parent, and tutors ask an admin to change their card
-- rather than editing it themselves.

-- 1. Bookings belong to an account. Name and email come from the profile, so
--    the anonymous contact columns become optional and are kept only for the
--    rows that predate this.
alter table public.booking_requests
  add column if not exists requester_id uuid references public.profiles(id) on delete cascade,
  add column if not exists subject text;

alter table public.booking_requests alter column name drop not null;
alter table public.booking_requests alter column email drop not null;

create index if not exists booking_requests_requester_idx
  on public.booking_requests (requester_id, created_at desc);

-- Every existing row is an intro-call request from the withdrawn flow.
delete from public.booking_requests;

drop policy if exists "Requesters can read their own bookings" on public.booking_requests;
create policy "Requesters can read their own bookings"
on public.booking_requests
for select
to authenticated
using (requester_id = (select auth.uid()));

-- 2. A tutor proposes card changes; an admin applies or rejects them. The
--    proposal is stored as the same shape the tutors table holds, so applying
--    it is a straight copy.
create table if not exists public.tutor_profile_requests (
  id bigint generated by default as identity primary key,
  tutor_registry_id text not null
    references public.tutors(registry_id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  payload jsonb not null default '{}'::jsonb,
  note text,
  status text not null default 'pending'
    check (status in ('pending', 'applied', 'rejected')),
  review_note text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  seen_by_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists tutor_profile_requests_open_idx
  on public.tutor_profile_requests (status, created_at desc);

alter table public.tutor_profile_requests enable row level security;

-- Writes go through the server routes with the service-role key.
revoke all on table public.tutor_profile_requests from anon, authenticated;
grant select on table public.tutor_profile_requests to authenticated;

drop policy if exists "Admins can read card requests" on public.tutor_profile_requests;
create policy "Admins can read card requests"
on public.tutor_profile_requests
for select
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and p.role = 'admin'
  )
);

drop policy if exists "Tutors can read their own card requests" on public.tutor_profile_requests;
create policy "Tutors can read their own card requests"
on public.tutor_profile_requests
for select
to authenticated
using (requested_by = (select auth.uid()));
