-- A classroom is the student/tutor pair that homework, lessons, and chat are
-- already keyed on. Giving it a row lets a parent join with a code the tutor
-- hands out, instead of being linked to the student's account.
create table if not exists public.classrooms (
  id bigint generated by default as identity primary key,
  join_code text not null unique,
  join_password text not null,
  student_id uuid not null references public.profiles(id) on delete cascade,
  tutor_registry_id text not null references public.tutors(registry_id) on delete cascade,
  title text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (student_id, tutor_registry_id)
);

create index if not exists classrooms_tutor_idx on public.classrooms (tutor_registry_id);

-- The student and tutor belong by construction; this records everyone else who
-- asked to join and whether the tutor let them in.
create table if not exists public.classroom_members (
  id bigint generated by default as identity primary key,
  classroom_id bigint not null references public.classrooms(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'parent' check (role in ('parent', 'student', 'tutor')),
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by uuid references public.profiles(id) on delete set null,
  unique (classroom_id, user_id)
);

create index if not exists classroom_members_user_idx on public.classroom_members (user_id, status);

alter table public.portal_sessions
  add column if not exists recording_url text;

alter table public.classrooms enable row level security;
alter table public.classroom_members enable row level security;

revoke all on table public.classrooms from public, anon, authenticated;
revoke all on table public.classroom_members from public, anon, authenticated;
grant select on table public.classrooms to authenticated;
grant select on table public.classroom_members to authenticated;

-- Membership drives every read, so it is a function to keep the policies flat.
-- The helper functions live in the private schema on this project.
create or replace function public.can_view_classroom(target_classroom_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.classrooms c
    where c.id = target_classroom_id
      and (
        c.student_id = (select auth.uid())
        or c.tutor_registry_id = (select private.current_tutor_registry_id())
        or exists (
          select 1 from public.classroom_members m
          where m.classroom_id = c.id
            and m.user_id = (select auth.uid())
            and m.status = 'approved'
        )
        or (select private.is_admin())
      )
  );
$$;

revoke all on function public.can_view_classroom(bigint) from public, anon;
grant execute on function public.can_view_classroom(bigint) to authenticated;

drop policy if exists "Members can read their classroom" on public.classrooms;
create policy "Members can read their classroom"
on public.classrooms for select to authenticated
using ((select public.can_view_classroom(id)));

drop policy if exists "Members and the tutor can read membership" on public.classroom_members;
create policy "Members and the tutor can read membership"
on public.classroom_members for select to authenticated
using (
  user_id = (select auth.uid())
  or (select public.can_view_classroom(classroom_id))
);

notify pgrst, 'reload schema';
