-- Parent (or any signed-in user) complaints route to the admin portal.
create table if not exists public.complaints (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null,
  status text not null default 'new'
    check (status in ('new', 'resolved')),
  admin_note text,
  handled_by uuid references public.profiles(id) on delete set null,
  handled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint complaints_body_check
    check (char_length(btrim(body)) between 2 and 4000)
);

create index if not exists complaints_status_created_idx
  on public.complaints (status, created_at desc);

alter table public.complaints enable row level security;

revoke all on table public.complaints from public, anon, authenticated;
grant select, insert, update on table public.complaints to authenticated;
grant usage, select on sequence public.complaints_id_seq to authenticated;

drop policy if exists "Authors and admins can read complaints" on public.complaints;
create policy "Authors and admins can read complaints"
on public.complaints
for select
to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "Users can file complaints" on public.complaints;
create policy "Users can file complaints"
on public.complaints
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Admins can update complaints" on public.complaints;
create policy "Admins can update complaints"
on public.complaints
for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

notify pgrst, 'reload schema';
